coverage:
  status:
    project:
      default:
        target: auto
        threshold: 1%
    patch:
      default:
        target: auto

ignore:
  - "src/pytest_threadpool/_version.py"

comment: false
